name: CI Build

on:
  push:
    branches:
      - net8.0

jobs:

  build_test_ios:

    name: Build and Package
    
    strategy:
      matrix:
        os: [macos-latest]
        configuration: [Release]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # avoid shallow clone

      - name: Set .NET SDK version
        if: contains(matrix.os, 'self-hosted') == false
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100-preview.6.23330.14"

      - name: Install workloads
        run: dotnet workload install ios maccatalyst

      - name: Build
        run: dotnet build ./MonoTouch.Dialog/Dotnet.MonoTouch.Dialog.csproj -c ${{ matrix.configuration }}

      - name: Pack
        run: dotnet pack ./MonoTouch.Dialog/Dotnet.MonoTouch.Dialog.csproj -c ${{ matrix.configuration }}
    