name: CI Build

on:
  push:
    branches:
      - net8.0

jobs:

  build_test_ios:

    name: Build and Package
    
    strategy:
      matrix:
        os: [macos-latest]
        configuration: [Release]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # avoid shallow clone

      - name: Set .NET SDK version
        if: contains(matrix.os, 'self-hosted') == false
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100-preview.7.23376.3"

      - name: Add GitHub Packages 'frankbuckley' Feed
        run: dotnet nuget update source frankbuckley --username "frankbuckley" --password ${{ secrets.PACKAGES_TOKEN }} --store-password-in-clear-text --source "https://nuget.pkg.github.com/frankbuckley/index.json" --configfile "./NuGet.config"

      - name: Install workloads
        run: dotnet workload install ios maccatalyst

      - name: Build
        run: dotnet build ./MonoTouch.Dialog/Dotnet.MonoTouch.Dialog.csproj -c ${{ matrix.configuration }}

      - name: Pack
        run: dotnet pack ./MonoTouch.Dialog/Dotnet.MonoTouch.Dialog.csproj -c ${{ matrix.configuration }}

      - name: Push Nuget Packages
        if: matrix.configuration == 'Release'
        run: Get-ChildItem *.nupkg -Recurse | ForEach-Object { &dotnet nuget push $_.FullName --source "frankbuckley" --api-key ${{ secrets.PACKAGES_TOKEN }} --skip-duplicate }
        shell: pwsh